# -*- coding: utf-8 -*-
"""crop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rbqQDjyGeBBodHU3kSxgCvFpZ4OQzeBM
"""

import os
import cv2
import matplotlib.pyplot as plt
import csv
import pandas as pd
# 100/376/401

def img_preprocess(img):
	gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
	thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_OTSU + cv2.THRESH_BINARY)[1]
	# Find contour and sort by contour area
	cnts = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
	cnts = cnts[0] if len(cnts) == 2 else cnts[1]
	cnts = sorted(cnts, key=cv2.contourArea, reverse=True)

	# Find bounding box and extract ROI
	for c in cnts:
	    x,y,w,h = cv2.boundingRect(c)
	    ROI = image[y:y+h, x:x+w]
	    break
	# ROI[:,:,0]=0
	# ROI[:,:,2]=0
	# ROI = cv2.cvtColor(ROI, cv2.COLOR_BGR2GRAY)
	return ROI

os.chdir("/home/ibmelab/Downloads/2023-06-11 11:55:26.344/DR")

filename1 = os.listdir("/home/ibmelab/Downloads/2023-06-11 11:55:26.344/archive/Evaluation_Set/Evaluation_Set")
df = pd.read_csv('trainLabels.csv')
df.info()

import matplotlib.pyplot as plt

os.chdir('/home/ibmelab/Downloads/2023-06-11 11:55:26.344/DR/eyepacs_preprocess/eyepacs_preprocess')

filenames = os.listdir()

for i in range(len(df)):
    image = cv2.imread(filename)
        cv2.imwrite(f'/home/ibmelab/Documents/ibme/RFMiD/train/DR1/{filename}.png',image)
for i in range(len(df)):
    filename = f"{df['ID'][i]}.png"
    image = cv2.imread(filename)
    new_image = img_preprocess(image)
    if  df['Disease_Risk'][i] == 0:
        cv2.imwrite(f'/home/ibmelab/Documents/ibme/RFMiD/train/AMD1/{filename}', new_image)
        df['ARMD'][i] == 1:
        cv2.imwrite(f'/home/ibmelab/Documents/ibme/RFMiD/test/AMD/{filename}', new_image)
    elif df['DR'][i] == 1:
            cv2.imwrite(f'/home/ibmelab/Documents/ibme/RFMiD/test/DR/{filename}', new_image)
    elif